clc;
clear;
data = load('./result_data/1127/EMR.mat');

x = data.Rt_set;
% y_pe = data.F2_Utility_2;
 y_pe = data.Random_Utility;
y_ra = data.Random_Utility;
y_tri = data.Triangle_Utility;
%plot(x,y_pe,'-b.',x,y_ra,'-g*',x,y_tri,'-r+');
plot(x,y_pe,'-b',x,y_ra,'-g',x,y_tri,'-r');
str1='\fontsize {16}\fontname {Helvetica}PESA';
str2='\fontsize {16}\fontname {Helvetica}Random';
str3='\fontsize {16}\fontname {Helvetica}Triangle';
hleg=legend(str1,str2,str3);
set(hleg,'Location','SouthEast');
hold on;
set(gca,'FontSize',16);
fh=figure(1);
set(fh, 'color', 'white'); 
xlabel('\fontsize {16}\fontname {Helvetica}The EMR Value');
ylabel('\fontsize {16}\fontname {Helvetica} Utility');
